### ISSUE TITLE
what kind of problem is this

### ISSUE THREAD

**Issue by eleven2021** [gilles437/0x-1inch-arb-bot#1]
profitable: true  netProfit:  3987491119570944 in string; 3987491119570944 inputAssetAmount: 58522619127241085899 outputAssetAmount: 58602276618360663131
Profitable?  Asset Order      Exchange Order  Input                   Output                  Profit                  Timestamp
-----------  ---------------  --------------  ----------------------  ----------------------  ----------------------  -------------------------
true         WETH, DAI, WETH  ZRX, 1Split     58.522619127241085899   58.602276618360663131   0.003987491119570944    2021-01-08T03:35:37+09:00

File is updated.
(node:13339) UnhandledPromiseRejectionWarning: Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/workspace/0x-1inch-arb-bot/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /workspace/0x-1inch-arb-bot/node_modules/web3-core-requestmanager/lib/index.js:291:36
    at XMLHttpRequest.request.onreadystatechange (/workspace/0x-1inch-arb-bot/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/workspace/0x-1inch-arb-bot/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/workspace/0x-1inch-arb-bot/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/workspace/0x-1inch-arb-bot/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/workspace/0x-1inch-arb-bot/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:13339) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13339) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by restorepro** [comment]
Did you add your "private key" in the .env file. Is it the infura secret key or the wallet private key. I wont enter my wallet private key if that is the case.
